### ISSUE TITLE
when run generate.py , inpdir

### ISSUE THREAD

**Issue by Zwhy0712** [ayush12gupta/Co-mod-gan-PyTorch-Implementation#5]
hi!
i have a problem.
What is the value of the inpdir parameter in generate.py when running the test? Did you create it yourself?

**Comment by ayush12gupta** [comment]
inpdir is the path to the directory containing 2 folders one for the images and another is the masks, for which paths are defined in the variable imgdir and maskdir in generate.py

**Comment by 123scott** [comment]
> 

So are these two folders created by yourself, and are the pictures in the files found by yourself?
